config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'ranking' => 'homes#rank', as: "rank"
  get 'latest' => 'homes#latest', as: "latest"
  get 'homes/:user_id' => 'homes#index', as: "homes"
  get 'policy' => 'homes#policy', as: "policy"
  get 'privacy' => 'homes#privacy', as: "privacy"
  get 'posts/category/:id' => 'posts#index', as: "posts_category"
  get 'thanks' => 'homes#thanks', as: "thanks"
  get 'browsing_histories/:user_id' => 'browsing_histories#index', as: "browsing_histories"
  get 'search' => 'posts#search', as: "search"
  resources :categorys, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :like, :edit, :update ,:destroy] do
    get :following, :followers, :like
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:index, :show, :search, :new, :create, :edit, :update, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :reports, only: [:index, :new, :create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true, length: {maximum: 15}
  validates :email , presence: true

  has_many :relationships, :dependent => :destroy
  has_many :followings, through: :relationships, source: :follow, :dependent => :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', :dependent => :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user, :dependent => :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :reports, :dependent => :destroy
  has_many :browsing_histories, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    if user_signed_in? && current_user.admin == true
      @users = User.where(admin: 'false').page(params[:page]).per(30)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def like
    user = User.find(params[:user_id])
    @likes = user.likes.page(params[:page]).per(30)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "更新に失敗しました。下記を修正し、再度お願いいたします。"
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:success] = "指定したユーザーを強制退会させました。"
      redirect_to users_path
    else
      flash.now[:alert] = "指定したユーザーの強制退会に失敗しました。再度お願いいたします。"
      render :index
    end
  end

  def following
    @user  = User.find(params[:user_id])
    @users = @user.followings.page(params[:page]).per(30)
    render 'follow'
  end

  def followers
    @user  = User.find(params[:user_id])
    @users = @user.followers.page(params[:page]).per(30)
    render 'follower'
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :profile_image, :encrypted_password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">

        <h2>登録情報編集</h2>

          <% if @user.errors.any? %>
            <ul>
              <h4><%= flash[:alert] %></h4>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with(model: @user, url: user_path, local: true) do |f| %>
            <p>ニックネーム <%= f.text_field :user_name %></p><br>
            <p>メールアドレス <%= f.email_field :email %></p><br>
            <%= f.submit "変更する", class: "btn" %>
          <% end %>

      </div>
    </div>
  </div>

app/views/users/follow.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h2>フォロー中</h2>
          <table class="table">
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user), class: "link" do %>
                      <%= user.user_name %>
                    <% end %>
                  </td>
                  <td>フォロー数：<%= user.followings.count %></td>
                  <td>フォロワー数：<%= user.followers.count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @users %>

      </div>
    </div>
  </div>

app/views/users/follower.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h2>フォロワー</h2>
          <table class="table">
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= link_to user_path(user), class: "link" do %>
                      <%= user.user_name %>
                    <% end %>
                  </td>
                  <td>フォロー数：<%= user.followings.count %></td>
                  <td>フォロワー数：<%= user.followers.count %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <%= paginate @users %>

      </div>
    </div>
  </div>

app/views/users/index.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4 text-center">
        <h2>ユーザー一覧</h2>
        <table class="table table-bordered">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user_path(user.id), class: "link" do %>
                    <%= user.user_name %>
                  <% end %>
                  <%= link_to "強制退会", user_path(user.id), method: :delete, data: { confirm: '本当に強制退会させますか？' }, class: "btn danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= paginate @users %>

      </div>
    </div>
  </div>

app/views/users/like.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h2>お気に入り一覧</h2>

        <% @likes.each do |like| %>
          <div class="item">
            <%= link_to post_path(like.post.id) do %>
              <%= attachment_image_tag like.post, :post_image, size: "200x200", align: "left", class: "img item-img" %><br>
              <h3 class="link"><%= like.post.post_title %></h3>
            <% end %>
            <p><%= like.post.category.category_name %>|<%= like.post.rate %>点</p><br>
            <p>投稿者:
              <%= link_to user_path(like.id), class: "link" do %>
                <%= like.user.user_name %>
              <% end %>
            </p><br clear="left">
          </div>
        <% end %>

        <%= paginate @likes, class: "paginate" %>

      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h2>マイページ</h2>
          <h4><%= flash[:alert] %></h4>
          <table class="table table-bordered table-hover">
            <tbody>
              <tr>
                <td>ニックネーム</td>
                <td>
                  <%= @user.user_name %>
                </td>
              </tr>
              <% if user_signed_in? && @user.id == current_user.id %>
                <tr>
                  <td>メールアドレス</td>
                  <td><%= @user.email %></td>
                </tr>
              <% end %>
              <tr>
                <td>
                  <%= link_to "フォロー", user_following_path(@user.id), class: "link" %>
                </td>
                <td>
                  <%= link_to user_following_path(@user.id), class: "link" do %>
                    <%= @user.followings.count %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= link_to "フォロワー", user_followers_path(@user.id), class: "link" %>
                </td>
                <td>
                  <%= link_to user_followers_path(@user.id), class: "link" do %>
                    <%= @user.followers.count %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>

          <% if user_signed_in? && @user.id == current_user.id %>
            <h4>登録情報変更</h4>
              <%= link_to edit_user_path(@user.id) do %>
                <button type="button" class="btn btn-default btn-block"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "link" do %>
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"> logout</span>
              <% end %>
          <% else %>
            <%= render 'relationships/follow', user: @user %>
          <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h4>投稿一覧</h4>
          <%= link_to "一覧を見る", homes_path(@user.id), class: "btn btn-default btn-block" %>
        <h4>お気に入り</h4>
          <%= link_to "一覧を見る", user_like_path(@user.id), class: "btn btn-default btn-block" %>
        <% if user_signed_in? && current_user == @user %>
          <h4>閲覧履歴</h4>
            <%= link_to "一覧を見る", browsing_histories_path(@user.id), class: "btn btn-default btn-block" %>
        <% end %>
    </div>
  </div>