config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'ranking' => 'homes#rank', as: "rank"
  get 'latest' => 'homes#latest', as: "latest"
  get 'homes/:user_id' => 'homes#index', as: "homes"
  get 'policy' => 'homes#policy', as: "policy"
  get 'privacy' => 'homes#privacy', as: "privacy"
  get 'posts/category/:id' => 'posts#index', as: "posts_category"
  get 'thanks' => 'homes#thanks', as: "thanks"
  get 'browsing_histories/:user_id' => 'browsing_histories#index', as: "browsing_histories"
  get 'search' => 'posts#search', as: "search"
  resources :categorys, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :like, :edit, :update ,:destroy] do
    get :following, :followers, :like
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:index, :show, :search, :new, :create, :edit, :update, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :reports, only: [:index, :new, :create, :destroy]

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :browsing_histories, dependent: :destroy

  attachment :post_image

  validates :post_title, presence: true, length: {maximum: 30 }
  validates :post_image, presence: true
  validates :category_id, presence: true
  validates :aroma, presence: true
  validates :acidity, presence: true
  validates :rich, presence: true
  validates :bitterness, presence: true
  validates :rate, :numericality => { :less_than_or_equal_to => 100 }, format: { with: /\A[a-z0-9]+\z/i }
  validates :body, presence: true, length: {maximum: 200}

  def self.search(search)
    if search.present?
      Post.where('post_title LIKE ?', "%#{search}%")
    else
      Post.none
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_categorys, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.all.page(params[:page]).per(10)
    @categorys = Category.all

    if params[:id]
      @category = Category.find(params[:id])
      @posts = @category.posts.order(created_at: :desc).page(params[:page]).per(10)
    end

  end

  def show
    @post = Post.find(params[:id])
    @category = @post.category
    @user = @post.user
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.order(created_at: :desc).page(params[:page]).per(10)
    @like = Like.new

    if user_signed_in?
      new_history = @post.browsing_histories.new
      new_history.user_id = current_user.id
    end

    if user_signed_in? && current_user.browsing_histories.exists?(post_id: params[:id])
      old_history = current_user.browsing_histories.find_by(post_id: params[:id])
      old_history.destroy
    end

    if user_signed_in?
      new_history.save
      histories_stock_limit = 10
      histories = current_user.browsing_histories.all
    end

    if user_signed_in? && histories.count > histories_stock_limit
      histories[0].destroy
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path
  end

  def search
    @posts = Post.search(params[:search]).page(params[:page]).per(10)

    if params[:search].empty?
      redirect_to root_path
    end

    if @posts.count == 0
      flash.now[:notice] = "ヒットする投稿がありませんでした。"
    end
  end

  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to root_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:success] = "レビューを投稿しました。"
      redirect_to post_path(@post.id)
    else
      flash.now[:alert] = "投稿に失敗しました。下記を修正し、再度お願いいたします。"
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
    if user_signed_in? && @post.user == current_user
      @user = @post.user
      @category = @post.category
    else
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "編集しました。"
      redirect_to post_path
    else
      flash.now[:alert] = "編集に失敗しました。下記を修正し、再度お願いいたします。"
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:success] = "レビューを削除しました。"
      redirect_to posts_path
    else
      flash.now[:alert] = "削除に失敗しました。再度お願いします。"
      redirect_to post_path(post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :category_id, :post_image, :post_title, :body, :aroma, :acidity, :rich, :bitterness, :rate)
  end

  def set_categorys
    @categorys = Category.all
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
  <% if current_user.already_liked?(post) %>
    <%= button_to 'お気に入り解除', post_likes_path(post), method: :delete, remote: true, class:"like_btn"  %>
  <% else %>
    <%= button_to 'お気に入り', post_likes_path(post), method: :post, remote: true, class:"like_btn"  %>
  <% end %>

app/views/posts/_post.html.erb
  <% posts.each do |post| %>
    <h3>
      <%= link_to post_path(post.id), class: "link" do %>
        <%= post.post_title %><br>
      <% end %>
    </h3>
    <%= link_to post_path(post.id) do %>
      <%= attachment_image_tag post, :post_image, align: "left", class: "img item-img" %><br>
    <% end %>
    <h4>カテゴリー:<%= post.category.category_name %></h4><br>
    <h4>評価:<%= post.rate %>点</h4><br clear="left">
  <% end %>

app/views/posts/_post_comment.html.erb
  <table class="table table-bordered">
    <thody>
      <tr>
        <td>
          <div>
            <%= link_to user_path(post_comment.user.id), class: "link" do %>
              <%= post_comment.user.user_name %>
            <% end %>
            <span class="comment-link">
              <% if user_signed_in? && post_comment.user == current_user %>
                <%= link_to "削除する", post_post_comment_path(post_id: post_comment.post.id, post_comment_id: post_comment.id), class: "link", method: :delete, remote: true %><br>
              <% elsif user_signed_in? && current_user.admin == true %>
                <%= link_to "削除する", post_post_comment_path(post_id: post_comment.post.id, post_comment_id: post_comment.id), class: "link", method: :delete, remote: true %><br>
              <% elsif user_signed_in? %>
                <%= link_to "通報する", new_report_path(post_comment_id: post_comment.id), class: "link" %><br>
              <% end %>
            </span>
          </div>
          <div class="time">
            <%= post_comment.created_at.to_s(:datetime_jp) %>にコメント済み
          </div>
          <div class="comment-title center">
            <strong><%= post_comment.title %></strong>
          </div>
          <div><%= post_comment.comment %></div>
        </td>
      </tr>
    </thody>
  </table>

app/views/posts/_search.html.erb
  <%= form_tag(search_path,:method => 'get') do %>
    <%= text_field_tag :search, "", class: 'input-mysize', placeholder: '調べたい口コミ' %>
    <button type="submit" class="button1">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button>
  <% end %>

app/views/posts/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h2>投稿編集</h2>

          <% if @post.errors.any? %>
            <ul>
              <h4><%= flash[:alert] %></h4>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with(model: @post, url: post_path, local: true) do |f| %>
            <ul>
              <li>商品画像</li>
              <li><%= f.attachment_field :post_image %></li>
              <li>商品名(30文字以内)</li>
              <li><%= f.text_field :post_title, class: "post-title" %></li>
              <li>商品カテゴリー <%= f.collection_select(:category_id, @categorys, :id, :category_name, {prompt: "--選択してください--"} ) %></li>
              <li>香り <%= f.select :aroma, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"香り" %></li>
              <li>酸味 <%= f.select :acidity, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"酸味" %></li>
              <li>コク <%= f.select :rich, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"コク" %></li>
              <li>苦味 <%= f.select :bitterness, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"苦味" %></li>
              <li>商品評価(英数字0~100まで)</li>
              <li><%= f.text_field :rate, class: "text-center", placeholder: "0〜100" %></li>
              <li>商品説明(おすすめポイントなど)(200字以内)</li>
              <li><%= f.text_area :body, class: "comment" %></li>
              <li>※すべての項目が必須項目です。</li>
              <%= f.submit "投稿する", :class=>"btn" %>
            </ul>
          <% end %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
  <div class="container">
    <div class="row">

      <%= render 'homes/list' %>

      <div class="col-xs-12 col-md-9 list">

        <h4><%= flash[:success] %></h4>

        <% if params[:id] %>
          <h2><%= @category.category_name %>(全<%= @posts.count %>件)</h2>
        <% else %>
          <h2>全て(全<%= @posts.count %>件)</h2>
        <% end %>

        <%= render 'post', posts: @posts %>

        <%= paginate @posts %>

      </div>
    </div>
  </div>

app/views/posts/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h2>新規投稿</h2>

          <% if @post.errors.any? %>
            <ul>
              <h4><%= flash[:alert] %></h4>
              <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with(model: @post, url: posts_path, local: true) do |f| %>
            <ul>
              <li>商品画像</li>
              <li><%= f.attachment_field :post_image %></li>
              <% if @post.post_image == true %>
                <%= attachment_image_tag @post, :post_image, class: "post_img" %>
              <% end %>
              <li>商品名(30文字以内)</li>
              <li><%= f.text_field :post_title, class: "post-title" %></li>
              <li>商品カテゴリー <%= f.collection_select(:category_id, @categorys, :id, :category_name, {prompt: "--選択してください--"} ) %></li>
              <li>香り <%= f.select :aroma, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"香り" %></li>
              <li>酸味 <%= f.select :acidity, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"酸味" %></li>
              <li>コク <%= f.select :rich, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"コク" %></li>
              <li>苦味 <%= f.select :bitterness, [["1", 1],["2", 2],["3", 3],["4",4],["5",5]], prompt:"苦味" %></li>
              <li>商品評価(英数字0~100まで)</li>
              <li><%= f.text_field :rate, class: "text-center", placeholder: "0〜100" %></li>
              <li>商品説明(おすすめポイントなど)(200字以内)</li>
              <li><%= f.text_area :body, class: "comment" %></li>
              <li>※すべての項目が必須項目です。</li>
              <%= f.submit "投稿する", :class=>"btn" %>
            </ul>
          <% end %>
      </div>
    </div>
  </div>

app/views/posts/search.html.erb
  <div class="container">
    <div class="row">

      <%= render 'homes/list' %>

      <div class="col-md-9 text-left list">
        <h2><%= params[:search] %>(全<%= @posts.count %>件)</h2>

        <h3><%= flash[:notice] %></h3>

        <%= render 'post', posts: @posts %>

        <%= paginate @posts %>

      </div>

    </div>
  </div>

app/views/posts/show.html.erb
  <div class="cantainer">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h4><%= flash[:alert] %></h4>
        <h4><%= flash[:success] %></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4"></div>

      <div class="col-lg-3 center">
        <%= attachment_image_tag @post, :post_image, class: "post_img" %>
      </div>

      <div class="col-lg-4 post-data">
        <p><strong>投稿者</strong>:
          <%= link_to user_path(@user.id), class: "link" do %>
            <%= @user.user_name %>
          <% end %>
        </p>
        <p>
          <strong>商品名</strong><br>
          <%= @post.post_title %>
        </p>
        <p><strong>カテゴリー</strong>:
          <%= link_to posts_category_path(@post.category.id), class: "link" do %>
            <%= @category.category_name %>
          <% end %>
        </p>
        <p><strong>投稿日</strong>: <%= @post.created_at.to_s(:datetime_jp) %></p>
        <p><strong>香り</strong>: <%= @post.aroma %>/5</p>
        <p><strong>酸味</strong>: <%= @post.acidity %>/5</p>
        <p><strong>コク</strong>: <%= @post.rich %>/5</p>
        <p><strong>苦味</strong>: <%= @post.bitterness %>/5</p>
        <p><strong>評価</strong>: <%= @post.rate %>点</p>
        <p>
          <strong>説明</strong> <br>
          <%= @post.body %>
        </p>

        <% if user_signed_in? %>
          <div id="likes_buttons_<%= @post.id %>">
            <%= render 'like', post: @post %>
          </div>
          <%= link_to "コメントする", new_post_post_comment_path(@post.id), class: "link" %> |
        <% end %>

        <% if user_signed_in? && current_user == @post.user %>
          <%= link_to "編集する", edit_post_path, class: "link" %> |
          <%= link_to "削除する", post_path, method: :delete, data: { confirm: '本当に削除しますか?' }, class: "link" %>
        <% elsif user_signed_in? && current_user.admin == true %>
          <%= link_to "削除する", post_path, method: :delete, data: { confirm: '本当に削除しますか?' }, class: "link" %>
        <% elsif user_signed_in? %>
          <%= link_to "通報する", new_report_path(post_id: @post.id), class: "link" %> |
        <% end %>
      </div>
    </div>
  </div>

  <div class="comments">
    <% @post_comments.each do |post_comment| %>
      <div id="comments_buttons_<%= post_comment.id %>">
        <%= render 'post_comment', post_comment:post_comment, post:@post %>
      </div>
    <% end %>
  </div>

  <div class="center">
    <%= paginate @post_comments %>
  </div>