config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'ranking' => 'homes#rank', as: "rank"
  get 'latest' => 'homes#latest', as: "latest"
  get 'homes/:user_id' => 'homes#index', as: "homes"
  get 'policy' => 'homes#policy', as: "policy"
  get 'privacy' => 'homes#privacy', as: "privacy"
  get 'posts/category/:id' => 'posts#index', as: "posts_category"
  get 'thanks' => 'homes#thanks', as: "thanks"
  get 'browsing_histories/:user_id' => 'browsing_histories#index', as: "browsing_histories"
  get 'search' => 'posts#search', as: "search"
  resources :categorys, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :like, :edit, :update ,:destroy] do
    get :following, :followers, :like
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:index, :show, :search, :new, :create, :edit, :update, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :reports, only: [:index, :new, :create, :destroy]

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :posts, dependent: :destroy

  validates :category_name, presence: true, length: {maximum: 15 }

end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController

  def index
    if user_signed_in? && current_user.admin == true
      @category  = Category.new
      @categorys = Category.all
    else
      redirect_to root_path
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "カテゴリーを作成しました。"
      redirect_to categorys_path
    else
      flash.now[:alert] = "カテゴリー作成に失敗しました。下記を修正し、再度お願いいたします。"
      @categorys = Category.all
      render :index
    end
  end

  def edit
    if user_signed_in? && current_user.admin == true
      @category = Category.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "カテゴリーを編集しました。"
      redirect_to categorys_path
    else
      flash.now[:alert] = "編集に失敗しました。下記を修正し、再度お願いいたします。"
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    if category.destroy
      flash[:success] = "カテゴリーを削除しました。"
      redirect_to categorys_path
    else
      flash.now[:alert] = "削除に失敗しました。再度お願いします"
      redirect_to categorys_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:category_name)
  end

end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/views/categorys/edit.html.erb
  <div class="comtainer">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h2>カテゴリー編集</h2>

          <% if @category.errors.any? %>
            <ul>
              <h4><%= flash[:alert] %></h4>
              <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with(model: @category, url: category_path, local: true) do |f| %>
            <p>新しいカテゴリー名: <%= f.text_field :category_name, value: "", placeholder:"カテゴリー名" %><p>
            <%= f.submit "変更を保存する", :class=>"btn" %>
          <% end %>
      </div>
    </div>
  </div>

app/views/categorys/index.html.erb
  <div class="comtainer">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6 text-center">
        <h2>カテゴリー作成</h2>

          <h4><%= flash[:success] %></h4>

          <% if @category.errors.any? %>
            <ul>
              <h4><%= flash[:alert] %></h4>
              <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with(model: @category, url: categorys_path, local: true) do |f| %>
            <%= f.text_field :category_name, placeholder:"カテゴリー名(15字以内)", class: "category-form" %>
            <%= f.submit "追加", :class=>"category-btn" %>
          <% end %>

        <h2>カテゴリー一覧</h2>

        <table class="table table-bordered">
          <tbody>
            <% @categorys.each do |category| %>
              <tr>
                <td>
                  <strong><%= category.category_name %></strong>
                  <%= link_to "編集する", edit_category_path(category.id), class: "btn active" %>
                  <%= link_to "削除する", category_path(category.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn active" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>