config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'ranking' => 'homes#rank', as: "rank"
  get 'latest' => 'homes#latest', as: "latest"
  get 'homes/:user_id' => 'homes#index', as: "homes"
  get 'policy' => 'homes#policy', as: "policy"
  get 'privacy' => 'homes#privacy', as: "privacy"
  get 'posts/category/:id' => 'posts#index', as: "posts_category"
  get 'thanks' => 'homes#thanks', as: "thanks"
  get 'browsing_histories/:user_id' => 'browsing_histories#index', as: "browsing_histories"
  get 'search' => 'posts#search', as: "search"
  resources :categorys, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :like, :edit, :update ,:destroy] do
    get :following, :followers, :like
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:index, :show, :search, :new, :create, :edit, :update, :destroy] do
    resources :post_comments, only: [:new, :create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :reports, only: [:index, :new, :create, :destroy]

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user
  belongs_to :post_comment, optional: true
  belongs_to :post, optional: true

  enum body: {性的な内容:1, 暴力的または不快な内容:2, 差別的または攻撃的な内容:3}

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    if user_signed_in? && current_user.admin == true
      @reports = Report.all.order(:post_id, :post_comment_id).page(params[:page]).per(30)
    else
      redirect_to root_path
    end
  end

  def new
    @report = Report.new
    unless user_signed_in?
      redirect_to root_path
    end

    if params[:post_id].present?
      @post = Post.find(params[:post_id])
    else
      @post_comment = PostComment.find(params[:post_comment_id])
    end
  end

  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id
    if @report.save
      redirect_to thanks_path
    else
      flash[:alert] = "通報に失敗しました。再度お願いします"
      redirect_to post_path(@report.post.id)
    end
  end

  def destroy
    report = Report.find(params[:id])
    if report.destroy
      flash[:success] = "削除しました。"
      redirect_to reports_path
    else
      flash[:alert] = "削除に失敗しました。再度お願いします"
      redirect_to reports_path
    end
  end

  private

  def report_params
    params.require(:report).permit(:user_id, :post_comment_id, :post_id, :body)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h4><%= flash[:alert] %></h4>
        <h4><%= flash[:success] %></h4>
        <table class="table table-bordered">
          <tbody>
            
            <tr>
              <th class="center">報告者</th>
              <th class="center">コメント作成者</th>
              <th class="center">タイトル</th>
              <th class="center">通報内容</th>
            </tr>

            <% @reports.each do |report| %>
              <% if report.post_id == nil %>
                <tr>
                  <td>
                    <%= link_to user_path(report.user.id), class: "link" do %>
                      <%= report.user.user_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_path(report.post_comment.user.id), class: "link" do %>
                      <%= report.post_comment.user.user_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to post_path(report.post_comment.post.id), class: "link" do %>
                      <%= report.post_comment.title %>
                    <% end %>
                  </td>
                  <td>
                    <%= report.body %>
                  </td>
                  <td><%= link_to "削除する", report_path(report.id), class: "link", method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
                </tr>
              <% end %>
            <% end %>

            <tr>
              <th class="center">報告者</th>
              <th class="center">投稿作成者</th>
              <th class="center">商品名</th>
              <th class="center">通報内容</th>
            </tr>

            <% @reports.each do |report| %>
              <% if report.post_id != nil %>
                <tr>
                  <td>
                    <%= link_to user_path(report.user.id), class: "link" do %>
                      <%= report.user.user_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_path(report.post.user.id), class: "link" do %>
                      <%= report.post.user.user_name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to post_path(report.post.id), class: "link" do %>
                      <%= report.post.post_title %>
                    <% end %>
                  </td>
                  <td>
                    <%= report.body %>
                  </td>
                  <td><%= link_to "削除する", report_path(report.id), class: "link", method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>

        <%= paginate @reports %>

      </div>
    </div>
  </div>

app/views/reports/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-5"></div>
      <div class="col-lg-6">
        <%= form_with(model: @report, url: reports_path, local: true) do |f| %>
          <%= f.radio_button :body, :性的な内容 %>
          <%= f.label :性的なコンテンツ %><br>
          <%= f.radio_button :body, :暴力的または不快な内容 %>
          <%= f.label :暴力的または不快な内容 %><br>
          <%= f.radio_button :body, :差別的または攻撃的な内容 %>
          <%= f.label :差別的または攻撃的な内容 %><br>
          <% if params[:post_comment_id] %>
            <%= f.hidden_field :post_comment_id, value: @post_comment.id %>
          <% else %>
            <%= f.hidden_field :post_id, value: @post.id %>
          <% end %>
          <p>※上記にない場合、未選択で報告してください。</p>
          <%= f.submit '報告', class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>